baseURL: "https://hackintoanetwork.com/"
languageCode: en-us
title: hackintoanetwork
theme: PaperMod

menu:
  main:
    - identifier: about
      name: about
      url: /CV.html
      weight: 10
    - identifier: home
      name: Home
      url: /
      weight: 20
    - identifier: blog
      name: Blog
      url: /blog
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 40
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 50
   

params:
  # theme
  showToc: false
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: false
    title: "hackintoanetwork"
    subtitle: Security Researcher, Hacker
    # imageUrl: "home/profile.jpg"
    # imageWidth: 151.8
    # imageHeight: 196.6
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # socialIcons:
  #   - name: "email"
  #     url: "hackintoanetwork@gmail.com"
  #   - name: "github"
  #     url: "https://github.com/hackintoanetwork"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
